@startuml
class FileSystemService {
    + FileSystemService(logger:LoggerService)
    + CanBackupNonPriorityFile(allJobs:List<BackupJobViewModel>, priorityExtensions:List<string>) : bool
    + GetAllFiles(path:string) : IEnumerable<string>
    + GetModifiedFilesSince(path:string, since:DateTime) : IEnumerable<string>
    + CopyFile(source:string, target:string) : void
    + GetDirectorySize(path:string) : long
}
FileSystemService --> "_logger" LoggerService
@enduml
