//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EASYSAVE_V2_0.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EASYSAVE_V2_0.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à === Create Backup Job ===.
        /// </summary>
        internal static string Create_backup_job {
            get {
                return ResourceManager.GetString("Create backup job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter job name:.
        /// </summary>
        internal static string Create_job_name {
            get {
                return ResourceManager.GetString("Create job name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter source path:.
        /// </summary>
        internal static string Create_job_path {
            get {
                return ResourceManager.GetString("Create job path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter target path:.
        /// </summary>
        internal static string Create_job_target {
            get {
                return ResourceManager.GetString("Create job target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter backup type (Complete/Differential):.
        /// </summary>
        internal static string Create_job_type {
            get {
                return ResourceManager.GetString("Create job type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter job IDs to execute (1 ;3 / 1-3):.
        /// </summary>
        internal static string Execute_backup_enter_job_id {
            get {
                return ResourceManager.GetString("Execute backup enter job id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error executing backup jobs:.
        /// </summary>
        internal static string Execute_backup_executing_error {
            get {
                return ResourceManager.GetString("Execute backup executing error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup jobs execution completed..
        /// </summary>
        internal static string Execute_backup_execution_completed {
            get {
                return ResourceManager.GetString("Execute backup execution completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à === Execute backup job ===.
        /// </summary>
        internal static string Execute_backup_job {
            get {
                return ResourceManager.GetString("Execute backup job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup jobs available..
        /// </summary>
        internal static string Execute_backup_no_available {
            get {
                return ResourceManager.GetString("Execute backup no available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No jobs selected..
        /// </summary>
        internal static string Execute_backup_no_job_select {
            get {
                return ResourceManager.GetString("Execute backup no job select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No valid job IDs entered..
        /// </summary>
        internal static string Execute_backup_no_valid_id {
            get {
                return ResourceManager.GetString("Execute backup no valid id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available backup jobs:.
        /// </summary>
        internal static string Execute_backup_print_list {
            get {
                return ResourceManager.GetString("Execute backup print list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name already exists.
        /// </summary>
        internal static string Job_name_already_exists {
            get {
                return ResourceManager.GetString("Job name already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        internal static string job_type_complete {
            get {
                return ResourceManager.GetString("job type complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string job_type_differential {
            get {
                return ResourceManager.GetString("job type differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid type. Please enter &apos;Complete&apos; or &apos;Differential&apos;.
        /// </summary>
        internal static string job_type_error {
            get {
                return ResourceManager.GetString("job type error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input cannot be empty. Please try again:.
        /// </summary>
        internal static string List_job_input_empty {
            get {
                return ResourceManager.GetString("List job input empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup jobs available..
        /// </summary>
        internal static string List_job_no_backup_available {
            get {
                return ResourceManager.GetString("List job no backup available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à === Backup Jobs List ===.
        /// </summary>
        internal static string List_job_title {
            get {
                return ResourceManager.GetString("List job title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Create backup job.
        /// </summary>
        internal static string Main_menu_create {
            get {
                return ResourceManager.GetString("Main menu create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Execute backup jobs.
        /// </summary>
        internal static string Main_menu_execute {
            get {
                return ResourceManager.GetString("Main menu execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Exit.
        /// </summary>
        internal static string Main_menu_exit {
            get {
                return ResourceManager.GetString("Main menu exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. List backup jobs.
        /// </summary>
        internal static string Main_menu_list {
            get {
                return ResourceManager.GetString("Main menu list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5. Select language FR/EN.
        /// </summary>
        internal static string Main_menu_select_language {
            get {
                return ResourceManager.GetString("Main menu select language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an option: .
        /// </summary>
        internal static string Main_menu_select_option {
            get {
                return ResourceManager.GetString("Main menu select option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have reached the maximum number of backup jobs (5)..
        /// </summary>
        internal static string Maximum_job_create {
            get {
                return ResourceManager.GetString("Maximum job create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To select your language enter &apos;FR&apos; or &apos;EN&apos;.
        /// </summary>
        internal static string Select_language {
            get {
                return ResourceManager.GetString("Select language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à === EasySave Main Menu ===.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
