@startuml
class StateService {
    - StateFile : string
    +  <<event>> StateUpdated : EventHandler<BackupState> 
    + StateService(logger:LoggerService)
    + UpdateState(jobName:string, status:string, progress:double, sourcePath:string, targetPath:string, totalFiles:int, totalSize:long, filesLeft:int, remainingSize:long, currentSourceFile:string, currentTargetFile:string) : void
    - LoadStates() : void
    - SaveStates() : void
    + GetAllStates() : IEnumerable<BackupState>
}
class "List`1"<T> {
}
StateService o-> "_states<BackupState>" "List`1"
StateService --> "_logger" LoggerService
@enduml
