@startuml
class Resources {
    <<internal>> Resources()
    <<internal>> {static} ApplicationLogs : string <<get>>
    <<internal>> {static} BackupType : string <<get>>
    <<internal>> {static} Browse : string <<get>>
    <<internal>> {static} BusinessSoftwarePopUp : string <<get>>
    <<internal>> {static} ButtonAdd : string <<get>>
    <<internal>> {static} ButtonApply : string <<get>>
    <<internal>> {static} ButtonCancel : string <<get>>
    <<internal>> {static} ButtonCreate : string <<get>>
    <<internal>> {static} ButtonDecrypt : string <<get>>
    <<internal>> {static} ButtonExAll : string <<get>>
    <<internal>> {static} ButtonExSelect : string <<get>>
    <<internal>> {static} ButtonHomeCreate : string <<get>>
    <<internal>> {static} ButtonHomeView : string <<get>>
    <<internal>> {static} ButtonLangEN : string <<get>>
    <<internal>> {static} ButtonLangFR : string <<get>>
    <<internal>> {static} ButtonSave : string <<get>>
    <<internal>> {static} ColumnJobName : string <<get>>
    <<internal>> {static} ColumnProgress : string <<get>>
    <<internal>> {static} ColumnStatus : string <<get>>
    <<internal>> {static} ColumnTarget : string <<get>>
    <<internal>> {static} Complete : string <<get>>
    <<internal>> {static} CreateJob : string <<get>>
    <<internal>> {static} CryptFile : string <<get>>
    <<internal>> {static} DecryptSuccess : string <<get>>
    <<internal>> {static} DecryptTitle : string <<get>>
    <<internal>> {static} Description : string <<get>>
    <<internal>> {static} Differential : string <<get>>
    <<internal>> {static} EditPannel : string <<get>>
    <<internal>> {static} FileToDecrypt : string <<get>>
    <<internal>> {static} InvalidFile : string <<get>>
    <<internal>> {static} JobName : string <<get>>
    <<internal>> {static} ListJobs : string <<get>>
    <<internal>> {static} PriorizeFile : string <<get>>
    <<internal>> {static} SelectedSoftware : string <<get>>
    <<internal>> {static} SettingCrypt : string <<get>>
    <<internal>> {static} SettingLanguage : string <<get>>
    <<internal>> {static} SettingLog : string <<get>>
    <<internal>> {static} SettingLogText : string <<get>>
    <<internal>> {static} SettingPriorization : string <<get>>
    <<internal>> {static} SettingSoftware : string <<get>>
    <<internal>> {static} SettingsTitle : string <<get>>
    <<internal>> {static} SoftText : string <<get>>
    <<internal>> {static} SourcePath : string <<get>>
    <<internal>> {static} TabCreate : string <<get>>
    <<internal>> {static} TabDecrypt : string <<get>>
    <<internal>> {static} TabHome : string <<get>>
    <<internal>> {static} TabJob : string <<get>>
    <<internal>> {static} TabSetting : string <<get>>
    <<internal>> {static} TargetPath : string <<get>>
    <<internal>> {static} UseCalc : string <<get>>
    <<internal>> {static} Welcome : string <<get>>
}
@enduml
