@startuml
class AppSettings {
    + Language : string <<get>> <<set>> = "EN"
}
class BusinessSoftware {
    + Name : string <<get>> <<set>> = "Aucun"
    + FullPath : string <<get>> <<set>> = ""
}
AppSettings o-> "LogFormat" LogFormat
AppSettings o-> "BusinessSoftware" BusinessSoftware
@enduml
