@startuml
class BackupState {
    + Name : string <<get>> <<set>>
    + Timestamp : string <<get>> <<set>>
    + State : string <<get>> <<set>>
    + TotalFiles : int <<get>> <<set>>
    + TotalSize : long <<get>> <<set>>
    + Progress : double <<get>> <<set>>
    + FilesRemaining : int <<get>> <<set>>
    + RemainingSize : long <<get>> <<set>>
    + CurrentSourceFile : string <<get>> <<set>>
    + CurrentTargetFile : string <<get>> <<set>>
    + SourcePath : string <<get>> <<set>>
    + TargetPath : string <<get>> <<set>>
}
@enduml
