@startuml
class BackupState {
    + Name : string <<get>> <<set>> = ""
    + SourcePath : string <<get>> <<set>> = ""
    + TargetPath : string <<get>> <<set>> = ""
    + State : string <<get>> <<set>> = "INACTIVE"
    + TotalFiles : int <<get>> <<set>> = 0
    + TotalSize : long <<get>> <<set>> = 0
    + FilesRemaining : int <<get>> <<set>> = 0
    + Progress : double <<get>> <<set>> = 0
}
@enduml
