@startuml
class BackupJob {
    + Id : int <<get>> <<set>>
    + <<required>> Name : string <<get>> <<set>>
    + <<required>> SourcePath : string <<get>> <<set>>
    + <<required>> TargetPath : string <<get>> <<set>>
    + <<required>> Type : string <<get>> <<set>>
}
@enduml
