@startuml
!include .\\Program.puml
!include .\\Models\AppSettings.puml
!include .\\Models\BackupJob.puml
!include .\\Models\BackupState.puml
!include .\\Models\JsonLogEntry.puml
!include .\\Services\FileSystemService.puml
!include .\\Services\LanguageService.puml
!include .\\Services\LoggerService.puml
!include .\\Services\SettingsService.puml
!include .\\Services\StateService.puml
!include .\\ViewModels\BackupJobViewModel.puml
!include .\\ViewModels\BackupManagerViewModel.puml
!include .\\ViewModels\MainViewModel.puml
!include .\\ViewModels\SettingsViewModel.puml
!include .\\Views\ConsoleView.puml
@enduml
