@startuml
class MainViewModel {
    - _selectedViewName : string
    - _logContent : string
    - _newJobName : string
    - _newJobSourcePath : string
    - _newJobTargetPath : string
    - _newJobType : string
    - _errorMessage : string
    - _currentLanguage : string = null
    + MainViewModel(backupManagerViewModel:BackupManagerViewModel, languageService:LanguageService, loggerService:LoggerService)
    - OnLogMessageAdded(sender:object, message:string) : void
    + SelectedViewName : string <<get>> <<set>>
    + LogContent : string <<get>> <<set>>
    + NewJobName : string <<get>> <<set>>
    + NewJobSourcePath : string <<get>> <<set>>
    + NewJobTargetPath : string <<get>> <<set>>
    + NewJobType : string <<get>> <<set>>
    + ErrorMessage : string <<get>> <<set>>
    + CurrentLanguage : string <<get>> <<set>>
    - _selectedLogFormat : string = "JSON"
    + SelectedLogFormat : string <<get>> <<set>>
    - Navigate(parameter:object) : void
    - InitLanguage() : void
    - CreateBackupJob(parameter:object) : void
    - CanCreateJob(parameter:object) : bool
    - BrowseSourcePath() : void
    - BrowseTargetPath() : void
    + GetLocalizedString(key:string) : string
}
ViewModelBase <|-- MainViewModel
MainViewModel --> "_backupManagerViewModel" BackupManagerViewModel
MainViewModel --> "_languageService" LanguageService
MainViewModel --> "_loggerService" LoggerService
MainViewModel --> "BackupManager" BackupManagerViewModel
@enduml
