@startuml
class Resources {
    <<internal>> Resources()
    <<internal>> {static} Create_backup_job : string <<get>>
    <<internal>> {static} Create_job_name : string <<get>>
    <<internal>> {static} Create_job_path : string <<get>>
    <<internal>> {static} Create_job_target : string <<get>>
    <<internal>> {static} Create_job_type : string <<get>>
    <<internal>> {static} Error_Log : string <<get>>
    <<internal>> {static} Execute_backup_enter_job_id : string <<get>>
    <<internal>> {static} Execute_backup_executing_error : string <<get>>
    <<internal>> {static} Execute_backup_execution_completed : string <<get>>
    <<internal>> {static} Execute_backup_job : string <<get>>
    <<internal>> {static} Execute_backup_no_available : string <<get>>
    <<internal>> {static} Execute_backup_no_job_select : string <<get>>
    <<internal>> {static} Execute_backup_no_valid_id : string <<get>>
    <<internal>> {static} Execute_backup_print_list : string <<get>>
    <<internal>> {static} Job_name_already_exists : string <<get>>
    <<internal>> {static} job_type_complete : string <<get>>
    <<internal>> {static} job_type_differential : string <<get>>
    <<internal>> {static} job_type_error : string <<get>>
    <<internal>> {static} List_job_input_empty : string <<get>>
    <<internal>> {static} List_job_no_backup_available : string <<get>>
    <<internal>> {static} List_job_title : string <<get>>
    <<internal>> {static} Main_menu_create : string <<get>>
    <<internal>> {static} Main_menu_execute : string <<get>>
    <<internal>> {static} Main_menu_exit : string <<get>>
    <<internal>> {static} Main_menu_list : string <<get>>
    <<internal>> {static} Main_menu_select_language : string <<get>>
    <<internal>> {static} Main_menu_select_log_settings : string <<get>>
    <<internal>> {static} Main_menu_select_option : string <<get>>
    <<internal>> {static} Maximum_job_create : string <<get>>
    <<internal>> {static} Select_language : string <<get>>
    <<internal>> {static} Select_Log : string <<get>>
    <<internal>> {static} Title : string <<get>>
}
@enduml
