@startuml
enum LogFormat {
    Json,
    Xml,
}
class JsonLogEntry {
    + Name : string <<get>> <<set>>
    + FileSource : string <<get>> <<set>>
    + FileTarget : string <<get>> <<set>>
    + FileSize : long <<get>> <<set>>
    + FileTransferTime : double <<get>> <<set>>
    + Time : string <<get>> <<set>>
    + EncryptionTime : double <<get>> <<set>>
}
class LoggerService {
    + LoggerService(logDirectory:string)
    + SetLogFormat(format:LogFormat) : void
    + Log(message:string) : void
    + LogError(errorMessage:string) : void
    + LogFileTransfer(backupName:string, sourcePath:string, targetPath:string, size:long, transferTimeMs:double) : void
}
LoggerService --> "_dailyLogger" DailyLogger

Class DailyLogger {
    - <<readonly>> _logDirectory : string
    + DailyLogger(logDirectory:string, logFormat:LogFormat)
    + SetLogFormat(format:LogFormat) : void
    + Log(entry:JsonLogEntry) : void
    - LogJson(entry:JsonLogEntry, path:string) : void
    - LogXml(entry:JsonLogEntry, path:string) : void
    + LogFileTransfer(backupName:string, sourcePath:string, targetPath:string, size:long, transferTimeMs:double, encryptionTimeMs:double) : void
}
@enduml
