@startuml
class BackupJobViewModel {
    + BackupJobViewModel(backupJob:BackupJob, fileSystemService:FileSystemService, loggerService:LoggerService, stateService:StateService)
    + Id : int <<get>>
    + Name : string <<get>>
    + SourcePath : string <<get>>
    + TargetPath : string <<get>>
    + Type : string <<get>>
    + Execute() : void
    - ExecuteCompleteBackup(files:List<string>, totalSize:long) : void
    - ExecuteDifferentialBackup() : void
    - CopyAndLog(sourceFile:string, targetFile:string) : double
    - GetLastCompleteBackupDate() : DateTime
}
BackupJobViewModel --> "_backupJob" BackupJob
BackupJobViewModel --> "_fileSystemService" FileSystemService
BackupJobViewModel --> "_loggerService" LoggerService
BackupJobViewModel --> "_stateService" StateService
BackupJobViewModel --> "Job" BackupJob
@enduml
