@startuml
class SettingsViewModel {
    + SettingsViewModel()
    + ChangeLogFormat(newFormat:LogFormat) : void
    + GetCurrentFormat() : LogFormat
}
SettingsViewModel --> "Settings" AppSettings
@enduml
